name: dev_community
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  bloc: ^8.1.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_svg: ^2.0.7
  flutter_dotenv: ^5.1.0
  flutter_html: ^3.0.0-beta.2
  http: ^1.1.0
  intl: ^0.18.1
  logger: ^2.0.1
  sqflite: ^2.3.0
  modal_bottom_sheet: ^2.1.2
  html_editor_enhanced: ^2.5.1
  json_annotation: ^4.8.1
  kakao_flutter_sdk: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
    - assets/svgs/skills/
    - assets/svgs/commons/
